# Generated by Django 4.2.2 on 2023-06-24 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=6)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.nationality')),
            ],
        ),
        migrations.CreateModel(
            name='Demon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.IntegerField()),
                ('difficulty_as_number', models.DecimalField(decimal_places=2, max_digits=6)),
                ('creators', models.ManyToManyField(to='main.creator')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.difficulty')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.player')),
            ],
        ),
        migrations.AddField(
            model_name='creator',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.nationality'),
        ),
    ]
