# Generated by Django 4.2.2 on 2023-06-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_demon_difficulty_as_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
