# Generated by Django 4.2.2 on 2023-06-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_creator_rating_alter_player_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='position_in_rating',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position_in_rating',
        ),
    ]
