# Generated by Django 4.2.2 on 2023-06-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_creator_position_in_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='rating',
            new_name='creator_points',
        ),
    ]
